#!/bin/bash

# 📝 SCRIPT DE DÉPLOIEMENT - SYSTÈME DE VÉRIFICATION PAR CODE À 6 CHIFFRES
# ==================================================================================
# Ce script déploie tous les composants nécessaires pour le nouveau système
# d'inscription avec code de vérification email.
#
# PRÉALABLES:
#   - Supabase CLI installée
#   - Authentification Supabase configurée (supabase login)
#   - Deno installé (pour tests locaux)
#
# ==================================================================================

echo "🚀 DÉPLOIEMENT DU SYSTÈME DE VÉRIFICATION PAR CODE"
echo "=================================================="

# ✅ ÉTAPE 1: Appliquer la migration SQL
echo ""
echo "📊 ÉTAPE 1: Création de la table email_verification_codes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Exécution de la migration:"
echo "  File: supabase/migrations/20260818_create_email_verification_codes.sql"
echo ""
echo "Options de déploiement:"
echo ""
echo "  Option A - Via Supabase CLI (recommandé):"
echo "    $ supabase db push"
echo ""
echo "  Option B - Manuelle (Supabase Dashboard):"
echo "    1. Aller à: SQL Editor"
echo "    2. Créer une nouvelle query"
echo "    3. Copier/coller le contenu du fichier .sql"
echo "    4. Exécuter"
echo ""

# ✅ ÉTAPE 2: Déployer les Supabase Functions
echo "🔧 ÉTAPE 2: Déploiement des Supabase Functions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3 fonctions à déployer:"
echo ""
echo "  1️⃣  send-verification-code"
echo "     Path: supabase/functions/send-verification-code"
echo "     Rôle: Génère et envoie le code par email"
echo ""
echo "     Déployer avec:"
echo "     $ supabase functions deploy send-verification-code"
echo ""
echo "  2️⃣  verify-code"
echo "     Path: supabase/functions/verify-code"
echo "     Rôle: Vérifie le code saisi par l'utilisateur"
echo ""
echo "     Déployer avec:"
echo "     $ supabase functions deploy verify-code"
echo ""
echo "  3️⃣  resend-verification-code"
echo "     Path: supabase/functions/resend-verification-code"
echo "     Rôle: Renvoie un nouveau code"
echo ""
echo "     Déployer avec:"
echo "     $ supabase functions deploy resend-verification-code"
echo ""
echo "  Ou déployer tous en même temps:"
echo "  $ supabase functions deploy"
echo ""

# ✅ ÉTAPE 3: Vérifier les variables d'environnement
echo "🔐 ÉTAPE 3: Variables d'Environnement"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Vérifier que .env contient:"
echo ""
echo "  EXPO_PUBLIC_SUPABASE_URL=https://your-project.supabase.co"
echo "  EXPO_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here"
echo ""
echo "Ces clés sont disponibles dans:"
echo "  Supabase Dashboard → Project Settings → API"
echo ""

# ✅ ÉTAPE 4: Configuration Email
echo "📧 ÉTAPE 4: Configuration Email Transactionnel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Vérifier que SMTP est configuré:"
echo ""
echo "  1. Aller à: Supabase Dashboard → Authentication → Email Templates"
echo "  2. Vérifier que l'email \"from\" est configuré"
echo "  3. Optionnel: Personnaliser les templates si nécessaire"
echo ""

# ✅ ÉTAPE 5: Modifications de production
echo "⚠️  ÉTAPE 5: Modifications pour Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "IMPORTANT: Enlever le code de la réponse API"
echo ""
echo "  Fichier: supabase/functions/send-verification-code/index.ts"
echo "  Ligne: ~72"
echo ""
echo "  AVANT (développement):"
echo "  return new Response(JSON.stringify({"
echo "    success: true,"
echo "    code: '123456'  ← À ENLEVER !"
echo "  }))"
echo ""
echo "  APRÈS (production):"
echo "  return new Response(JSON.stringify({"
echo "    success: true,"
echo "    message: 'Verification code sent successfully'"
echo "  }))"
echo ""

# ✅ ÉTAPE 6: Tests
echo "🧪 ÉTAPE 6: Tests Avant Déploiement"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Tests à effectuer:"
echo ""
echo "  ✓ Test Happy Path:"
echo "    1. Aller à /auth/signup"
echo "    2. Remplir le formulaire"
echo "    3. Cliquer 'S'inscrire'"
echo "    4. Recevoir le code par email"
echo "    5. Saisir le code (6 champs)"
echo "    6. Vérifier la redirection vers login"
echo "    7. Se connecter avec email/password"
echo ""
echo "  ✓ Test Code Expiré:"
echo "    1. Signup"
echo "    2. Attendre >20 minutes"
echo "    3. Tenter de vérifier le code"
echo "    4. Vérifier le message d'erreur"
echo ""
echo "  ✓ Test Renvoi:"
echo "    1. Signup"
echo "    2. Cliquer 'Renvoyer un code'"
echo "    3. Recevoir un nouveau code"
echo "    4. Utiliser le nouveau code pour vérifier"
echo ""
echo "  ✓ Test Code Invalide:"
echo "    1. Signup"
echo "    2. Saisir un code faux"
echo "    3. Vérifier le message d'erreur"
echo "    4. Vérifier que tentatives -1"
echo ""

# ✅ ÉTAPE 7: Monitoring
echo "📊 ÉTAPE 7: Monitoring en Production"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Après le déploiement, vérifier:"
echo ""
echo "  1. Logs des Supabase Functions:"
echo "     Supabase Dashboard → Functions → Logs"
echo ""
echo "  2. Table email_verification_codes:"
echo "     Supabase Dashboard → SQL Editor"
echo "     SELECT * FROM email_verification_codes LIMIT 10;"
echo ""
echo "  3. Utilisateurs créés:"
echo "     Vérifier que email_confirmed_at est rempli après vérification"
echo ""
echo "  4. Erreurs potentielles:"
echo "     - Email non reçu → Vérifier SMTP"
echo "     - Fonction timeout → Vérifier connexion BD"
echo "     - RLS error → Vérifier policies de la table"
echo ""

# ✅ RÉCAPITULATIF
echo ""
echo "════════════════════════════════════════════════════════"
echo "📋 RÉCAPITULATIF DES COMMANDES"
echo "════════════════════════════════════════════════════════"
echo ""
echo "# 1. Mettre à jour la base de données"
echo "supabase db push"
echo ""
echo "# 2. Déployer les fonctions"
echo "supabase functions deploy"
echo ""
echo "# 3. Vérifier le statut"
echo "supabase functions list"
echo ""
echo "# 4. Tester une fonction localement"
echo "supabase functions start"
echo ""

echo ""
echo "✅ DÉPLOIEMENT PRÊT !"
echo ""
echo "Fichiers concernés:"
echo "  📁 supabase/migrations/20260818_create_email_verification_codes.sql"
echo "  📁 supabase/functions/send-verification-code/index.ts"
echo "  📁 supabase/functions/verify-code/index.ts"
echo "  📁 supabase/functions/resend-verification-code/index.ts"
echo "  📁 app/auth/signup.tsx (modifié)"
echo "  📁 app/auth/verify-code.tsx (nouveau)"
echo ""
echo "Documentation:"
echo "  📄 VERIFICATION_CODE_SYSTEM_DOCUMENTATION.md"
echo "  📄 IMPLEMENTATION_SUMMARY.md"
echo ""
echo "════════════════════════════════════════════════════════"
